// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomResponse.proto

#ifndef PROTOBUF_RoomResponse_2eproto__INCLUDED
#define PROTOBUF_RoomResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "data.pb.h"
#include "RoomData.pb.h"
// @@protoc_insertion_point(includes)

namespace RoomResponse {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RoomResponse_2eproto();
void protobuf_AssignDesc_RoomResponse_2eproto();
void protobuf_ShutdownFile_RoomResponse_2eproto();

class RoomInfoResponse;

// ===================================================================

class RoomInfoResponse : public ::google::protobuf::Message {
 public:
  RoomInfoResponse();
  virtual ~RoomInfoResponse();

  RoomInfoResponse(const RoomInfoResponse& from);

  inline RoomInfoResponse& operator=(const RoomInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoomInfoResponse& default_instance();

  void Swap(RoomInfoResponse* other);

  // implements Message ----------------------------------------------

  RoomInfoResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RoomInfoResponse& from);
  void MergeFrom(const RoomInfoResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .RoomData.RoomInfo room_info = 1;
  inline bool has_room_info() const;
  inline void clear_room_info();
  static const int kRoomInfoFieldNumber = 1;
  inline const ::RoomData::RoomInfo& room_info() const;
  inline ::RoomData::RoomInfo* mutable_room_info();
  inline ::RoomData::RoomInfo* release_room_info();
  inline void set_allocated_room_info(::RoomData::RoomInfo* room_info);

  // @@protoc_insertion_point(class_scope:RoomResponse.RoomInfoResponse)
 private:
  inline void set_has_room_info();
  inline void clear_has_room_info();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::RoomData::RoomInfo* room_info_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_RoomResponse_2eproto();
  friend void protobuf_AssignDesc_RoomResponse_2eproto();
  friend void protobuf_ShutdownFile_RoomResponse_2eproto();

  void InitAsDefaultInstance();
  static RoomInfoResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// RoomInfoResponse

// optional .RoomData.RoomInfo room_info = 1;
inline bool RoomInfoResponse::has_room_info() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoomInfoResponse::set_has_room_info() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoomInfoResponse::clear_has_room_info() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RoomInfoResponse::clear_room_info() {
  if (room_info_ != NULL) room_info_->::RoomData::RoomInfo::Clear();
  clear_has_room_info();
}
inline const ::RoomData::RoomInfo& RoomInfoResponse::room_info() const {
  return room_info_ != NULL ? *room_info_ : *default_instance_->room_info_;
}
inline ::RoomData::RoomInfo* RoomInfoResponse::mutable_room_info() {
  set_has_room_info();
  if (room_info_ == NULL) room_info_ = new ::RoomData::RoomInfo;
  return room_info_;
}
inline ::RoomData::RoomInfo* RoomInfoResponse::release_room_info() {
  clear_has_room_info();
  ::RoomData::RoomInfo* temp = room_info_;
  room_info_ = NULL;
  return temp;
}
inline void RoomInfoResponse::set_allocated_room_info(::RoomData::RoomInfo* room_info) {
  delete room_info_;
  room_info_ = room_info;
  if (room_info) {
    set_has_room_info();
  } else {
    clear_has_room_info();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace RoomResponse

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RoomResponse_2eproto__INCLUDED
