// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserListResponse.proto

#ifndef PROTOBUF_UserListResponse_2eproto__INCLUDED
#define PROTOBUF_UserListResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "data.pb.h"
// @@protoc_insertion_point(includes)

namespace UserListResponse {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UserListResponse_2eproto();
void protobuf_AssignDesc_UserListResponse_2eproto();
void protobuf_ShutdownFile_UserListResponse_2eproto();

class FollowListResponse;
class FollowedListResponse;

// ===================================================================

class FollowListResponse : public ::google::protobuf::Message {
 public:
  FollowListResponse();
  virtual ~FollowListResponse();

  FollowListResponse(const FollowListResponse& from);

  inline FollowListResponse& operator=(const FollowListResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FollowListResponse& default_instance();

  void Swap(FollowListResponse* other);

  // implements Message ----------------------------------------------

  FollowListResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FollowListResponse& from);
  void MergeFrom(const FollowListResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Data.List people_list = 1;
  inline bool has_people_list() const;
  inline void clear_people_list();
  static const int kPeopleListFieldNumber = 1;
  inline const ::Data::List& people_list() const;
  inline ::Data::List* mutable_people_list();
  inline ::Data::List* release_people_list();
  inline void set_allocated_people_list(::Data::List* people_list);

  // @@protoc_insertion_point(class_scope:UserListResponse.FollowListResponse)
 private:
  inline void set_has_people_list();
  inline void clear_has_people_list();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::Data::List* people_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_UserListResponse_2eproto();
  friend void protobuf_AssignDesc_UserListResponse_2eproto();
  friend void protobuf_ShutdownFile_UserListResponse_2eproto();

  void InitAsDefaultInstance();
  static FollowListResponse* default_instance_;
};
// -------------------------------------------------------------------

class FollowedListResponse : public ::google::protobuf::Message {
 public:
  FollowedListResponse();
  virtual ~FollowedListResponse();

  FollowedListResponse(const FollowedListResponse& from);

  inline FollowedListResponse& operator=(const FollowedListResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FollowedListResponse& default_instance();

  void Swap(FollowedListResponse* other);

  // implements Message ----------------------------------------------

  FollowedListResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FollowedListResponse& from);
  void MergeFrom(const FollowedListResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Data.List people_list = 1;
  inline bool has_people_list() const;
  inline void clear_people_list();
  static const int kPeopleListFieldNumber = 1;
  inline const ::Data::List& people_list() const;
  inline ::Data::List* mutable_people_list();
  inline ::Data::List* release_people_list();
  inline void set_allocated_people_list(::Data::List* people_list);

  // @@protoc_insertion_point(class_scope:UserListResponse.FollowedListResponse)
 private:
  inline void set_has_people_list();
  inline void clear_has_people_list();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::Data::List* people_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_UserListResponse_2eproto();
  friend void protobuf_AssignDesc_UserListResponse_2eproto();
  friend void protobuf_ShutdownFile_UserListResponse_2eproto();

  void InitAsDefaultInstance();
  static FollowedListResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// FollowListResponse

// optional .Data.List people_list = 1;
inline bool FollowListResponse::has_people_list() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FollowListResponse::set_has_people_list() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FollowListResponse::clear_has_people_list() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FollowListResponse::clear_people_list() {
  if (people_list_ != NULL) people_list_->::Data::List::Clear();
  clear_has_people_list();
}
inline const ::Data::List& FollowListResponse::people_list() const {
  return people_list_ != NULL ? *people_list_ : *default_instance_->people_list_;
}
inline ::Data::List* FollowListResponse::mutable_people_list() {
  set_has_people_list();
  if (people_list_ == NULL) people_list_ = new ::Data::List;
  return people_list_;
}
inline ::Data::List* FollowListResponse::release_people_list() {
  clear_has_people_list();
  ::Data::List* temp = people_list_;
  people_list_ = NULL;
  return temp;
}
inline void FollowListResponse::set_allocated_people_list(::Data::List* people_list) {
  delete people_list_;
  people_list_ = people_list;
  if (people_list) {
    set_has_people_list();
  } else {
    clear_has_people_list();
  }
}

// -------------------------------------------------------------------

// FollowedListResponse

// optional .Data.List people_list = 1;
inline bool FollowedListResponse::has_people_list() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FollowedListResponse::set_has_people_list() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FollowedListResponse::clear_has_people_list() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FollowedListResponse::clear_people_list() {
  if (people_list_ != NULL) people_list_->::Data::List::Clear();
  clear_has_people_list();
}
inline const ::Data::List& FollowedListResponse::people_list() const {
  return people_list_ != NULL ? *people_list_ : *default_instance_->people_list_;
}
inline ::Data::List* FollowedListResponse::mutable_people_list() {
  set_has_people_list();
  if (people_list_ == NULL) people_list_ = new ::Data::List;
  return people_list_;
}
inline ::Data::List* FollowedListResponse::release_people_list() {
  clear_has_people_list();
  ::Data::List* temp = people_list_;
  people_list_ = NULL;
  return temp;
}
inline void FollowedListResponse::set_allocated_people_list(::Data::List* people_list) {
  delete people_list_;
  people_list_ = people_list;
  if (people_list) {
    set_has_people_list();
  } else {
    clear_has_people_list();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace UserListResponse

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UserListResponse_2eproto__INCLUDED
