// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserResponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "UserResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace UserResponse {

namespace {

const ::google::protobuf::Descriptor* LoginResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoginResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* DetailResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DetailResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* UsernameExistResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UsernameExistResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* UserMessageResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UserMessageResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* IsExistNewMessageResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  IsExistNewMessageResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_UserResponse_2eproto() {
  protobuf_AddDesc_UserResponse_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "UserResponse.proto");
  GOOGLE_CHECK(file != NULL);
  LoginResponse_descriptor_ = file->message_type(0);
  static const int LoginResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResponse, sid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResponse, user_info_),
  };
  LoginResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LoginResponse_descriptor_,
      LoginResponse::default_instance_,
      LoginResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LoginResponse));
  DetailResponse_descriptor_ = file->message_type(1);
  static const int DetailResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DetailResponse, is_follow_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DetailResponse, user_info_),
  };
  DetailResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DetailResponse_descriptor_,
      DetailResponse::default_instance_,
      DetailResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DetailResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DetailResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DetailResponse));
  UsernameExistResponse_descriptor_ = file->message_type(2);
  static const int UsernameExistResponse_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UsernameExistResponse, is_exist_),
  };
  UsernameExistResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UsernameExistResponse_descriptor_,
      UsernameExistResponse::default_instance_,
      UsernameExistResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UsernameExistResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UsernameExistResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UsernameExistResponse));
  UserMessageResponse_descriptor_ = file->message_type(3);
  static const int UserMessageResponse_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserMessageResponse, sender_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserMessageResponse, recipient_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserMessageResponse, message_info_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserMessageResponse, message_count_),
  };
  UserMessageResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UserMessageResponse_descriptor_,
      UserMessageResponse::default_instance_,
      UserMessageResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserMessageResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserMessageResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UserMessageResponse));
  IsExistNewMessageResponse_descriptor_ = file->message_type(4);
  static const int IsExistNewMessageResponse_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IsExistNewMessageResponse, is_exist_),
  };
  IsExistNewMessageResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      IsExistNewMessageResponse_descriptor_,
      IsExistNewMessageResponse::default_instance_,
      IsExistNewMessageResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IsExistNewMessageResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IsExistNewMessageResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(IsExistNewMessageResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_UserResponse_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LoginResponse_descriptor_, &LoginResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DetailResponse_descriptor_, &DetailResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UsernameExistResponse_descriptor_, &UsernameExistResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UserMessageResponse_descriptor_, &UserMessageResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    IsExistNewMessageResponse_descriptor_, &IsExistNewMessageResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_UserResponse_2eproto() {
  delete LoginResponse::default_instance_;
  delete LoginResponse_reflection_;
  delete DetailResponse::default_instance_;
  delete DetailResponse_reflection_;
  delete UsernameExistResponse::default_instance_;
  delete UsernameExistResponse_reflection_;
  delete UserMessageResponse::default_instance_;
  delete UserMessageResponse_reflection_;
  delete IsExistNewMessageResponse::default_instance_;
  delete IsExistNewMessageResponse_reflection_;
}

void protobuf_AddDesc_UserResponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::UserData::protobuf_AddDesc_UserData_2eproto();
  ::MessageData::protobuf_AddDesc_MessageData_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022UserResponse.proto\022\014UserResponse\032\016User"
    "Data.proto\032\021MessageData.proto\"D\n\rLoginRe"
    "sponse\022\013\n\003sid\030\001 \001(\t\022&\n\tUser_Info\030\002 \001(\0132\023"
    ".UserData.User_Info\"K\n\016DetailResponse\022\021\n"
    "\tis_follow\030\001 \001(\010\022&\n\tUser_Info\030\002 \001(\0132\023.Us"
    "erData.User_Info\")\n\025UsernameExistRespons"
    "e\022\020\n\010is_exist\030\001 \001(\010\"\252\001\n\023UserMessageRespo"
    "nse\022#\n\006sender\030\001 \001(\0132\023.UserData.User_Info"
    "\022&\n\trecipient\030\002 \001(\0132\023.UserData.User_Info"
    "\022/\n\014message_info\030\003 \001(\0132\031.MessageData.Mes"
    "sage_Info\022\025\n\rmessage_count\030\004 \001(\005\"-\n\031IsEx"
    "istNewMessageResponse\022\020\n\010is_exist\030\001 \001(\010", 479);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "UserResponse.proto", &protobuf_RegisterTypes);
  LoginResponse::default_instance_ = new LoginResponse();
  DetailResponse::default_instance_ = new DetailResponse();
  UsernameExistResponse::default_instance_ = new UsernameExistResponse();
  UserMessageResponse::default_instance_ = new UserMessageResponse();
  IsExistNewMessageResponse::default_instance_ = new IsExistNewMessageResponse();
  LoginResponse::default_instance_->InitAsDefaultInstance();
  DetailResponse::default_instance_->InitAsDefaultInstance();
  UsernameExistResponse::default_instance_->InitAsDefaultInstance();
  UserMessageResponse::default_instance_->InitAsDefaultInstance();
  IsExistNewMessageResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_UserResponse_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_UserResponse_2eproto {
  StaticDescriptorInitializer_UserResponse_2eproto() {
    protobuf_AddDesc_UserResponse_2eproto();
  }
} static_descriptor_initializer_UserResponse_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int LoginResponse::kSidFieldNumber;
const int LoginResponse::kUserInfoFieldNumber;
#endif  // !_MSC_VER

LoginResponse::LoginResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void LoginResponse::InitAsDefaultInstance() {
  user_info_ = const_cast< ::UserData::User_Info*>(&::UserData::User_Info::default_instance());
}

LoginResponse::LoginResponse(const LoginResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void LoginResponse::SharedCtor() {
  _cached_size_ = 0;
  sid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  user_info_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LoginResponse::~LoginResponse() {
  SharedDtor();
}

void LoginResponse::SharedDtor() {
  if (sid_ != &::google::protobuf::internal::kEmptyString) {
    delete sid_;
  }
  if (this != default_instance_) {
    delete user_info_;
  }
}

void LoginResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoginResponse_descriptor_;
}

const LoginResponse& LoginResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UserResponse_2eproto();
  return *default_instance_;
}

LoginResponse* LoginResponse::default_instance_ = NULL;

LoginResponse* LoginResponse::New() const {
  return new LoginResponse;
}

void LoginResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_sid()) {
      if (sid_ != &::google::protobuf::internal::kEmptyString) {
        sid_->clear();
      }
    }
    if (has_user_info()) {
      if (user_info_ != NULL) user_info_->::UserData::User_Info::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool LoginResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string sid = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->sid().data(), this->sid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_User_Info;
        break;
      }

      // optional .UserData.User_Info User_Info = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_User_Info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_user_info()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void LoginResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string sid = 1;
  if (has_sid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sid().data(), this->sid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->sid(), output);
  }

  // optional .UserData.User_Info User_Info = 2;
  if (has_user_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->user_info(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* LoginResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string sid = 1;
  if (has_sid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sid().data(), this->sid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->sid(), target);
  }

  // optional .UserData.User_Info User_Info = 2;
  if (has_user_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->user_info(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int LoginResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string sid = 1;
    if (has_sid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sid());
    }

    // optional .UserData.User_Info User_Info = 2;
    if (has_user_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->user_info());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoginResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const LoginResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const LoginResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void LoginResponse::MergeFrom(const LoginResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_sid()) {
      set_sid(from.sid());
    }
    if (from.has_user_info()) {
      mutable_user_info()->::UserData::User_Info::MergeFrom(from.user_info());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void LoginResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoginResponse::CopyFrom(const LoginResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginResponse::IsInitialized() const {

  return true;
}

void LoginResponse::Swap(LoginResponse* other) {
  if (other != this) {
    std::swap(sid_, other->sid_);
    std::swap(user_info_, other->user_info_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata LoginResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoginResponse_descriptor_;
  metadata.reflection = LoginResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int DetailResponse::kIsFollowFieldNumber;
const int DetailResponse::kUserInfoFieldNumber;
#endif  // !_MSC_VER

DetailResponse::DetailResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DetailResponse::InitAsDefaultInstance() {
  user_info_ = const_cast< ::UserData::User_Info*>(&::UserData::User_Info::default_instance());
}

DetailResponse::DetailResponse(const DetailResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DetailResponse::SharedCtor() {
  _cached_size_ = 0;
  is_follow_ = false;
  user_info_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DetailResponse::~DetailResponse() {
  SharedDtor();
}

void DetailResponse::SharedDtor() {
  if (this != default_instance_) {
    delete user_info_;
  }
}

void DetailResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DetailResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DetailResponse_descriptor_;
}

const DetailResponse& DetailResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UserResponse_2eproto();
  return *default_instance_;
}

DetailResponse* DetailResponse::default_instance_ = NULL;

DetailResponse* DetailResponse::New() const {
  return new DetailResponse;
}

void DetailResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    is_follow_ = false;
    if (has_user_info()) {
      if (user_info_ != NULL) user_info_->::UserData::User_Info::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DetailResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool is_follow = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_follow_)));
          set_has_is_follow();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_User_Info;
        break;
      }

      // optional .UserData.User_Info User_Info = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_User_Info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_user_info()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DetailResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool is_follow = 1;
  if (has_is_follow()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->is_follow(), output);
  }

  // optional .UserData.User_Info User_Info = 2;
  if (has_user_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->user_info(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DetailResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bool is_follow = 1;
  if (has_is_follow()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->is_follow(), target);
  }

  // optional .UserData.User_Info User_Info = 2;
  if (has_user_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->user_info(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DetailResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool is_follow = 1;
    if (has_is_follow()) {
      total_size += 1 + 1;
    }

    // optional .UserData.User_Info User_Info = 2;
    if (has_user_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->user_info());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DetailResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DetailResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DetailResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DetailResponse::MergeFrom(const DetailResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_is_follow()) {
      set_is_follow(from.is_follow());
    }
    if (from.has_user_info()) {
      mutable_user_info()->::UserData::User_Info::MergeFrom(from.user_info());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DetailResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DetailResponse::CopyFrom(const DetailResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DetailResponse::IsInitialized() const {

  return true;
}

void DetailResponse::Swap(DetailResponse* other) {
  if (other != this) {
    std::swap(is_follow_, other->is_follow_);
    std::swap(user_info_, other->user_info_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DetailResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DetailResponse_descriptor_;
  metadata.reflection = DetailResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int UsernameExistResponse::kIsExistFieldNumber;
#endif  // !_MSC_VER

UsernameExistResponse::UsernameExistResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void UsernameExistResponse::InitAsDefaultInstance() {
}

UsernameExistResponse::UsernameExistResponse(const UsernameExistResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void UsernameExistResponse::SharedCtor() {
  _cached_size_ = 0;
  is_exist_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UsernameExistResponse::~UsernameExistResponse() {
  SharedDtor();
}

void UsernameExistResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void UsernameExistResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UsernameExistResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UsernameExistResponse_descriptor_;
}

const UsernameExistResponse& UsernameExistResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UserResponse_2eproto();
  return *default_instance_;
}

UsernameExistResponse* UsernameExistResponse::default_instance_ = NULL;

UsernameExistResponse* UsernameExistResponse::New() const {
  return new UsernameExistResponse;
}

void UsernameExistResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    is_exist_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UsernameExistResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool is_exist = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_exist_)));
          set_has_is_exist();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void UsernameExistResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool is_exist = 1;
  if (has_is_exist()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->is_exist(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* UsernameExistResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bool is_exist = 1;
  if (has_is_exist()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->is_exist(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int UsernameExistResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool is_exist = 1;
    if (has_is_exist()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UsernameExistResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UsernameExistResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UsernameExistResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UsernameExistResponse::MergeFrom(const UsernameExistResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_is_exist()) {
      set_is_exist(from.is_exist());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UsernameExistResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UsernameExistResponse::CopyFrom(const UsernameExistResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UsernameExistResponse::IsInitialized() const {

  return true;
}

void UsernameExistResponse::Swap(UsernameExistResponse* other) {
  if (other != this) {
    std::swap(is_exist_, other->is_exist_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UsernameExistResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UsernameExistResponse_descriptor_;
  metadata.reflection = UsernameExistResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int UserMessageResponse::kSenderFieldNumber;
const int UserMessageResponse::kRecipientFieldNumber;
const int UserMessageResponse::kMessageInfoFieldNumber;
const int UserMessageResponse::kMessageCountFieldNumber;
#endif  // !_MSC_VER

UserMessageResponse::UserMessageResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void UserMessageResponse::InitAsDefaultInstance() {
  sender_ = const_cast< ::UserData::User_Info*>(&::UserData::User_Info::default_instance());
  recipient_ = const_cast< ::UserData::User_Info*>(&::UserData::User_Info::default_instance());
  message_info_ = const_cast< ::MessageData::Message_Info*>(&::MessageData::Message_Info::default_instance());
}

UserMessageResponse::UserMessageResponse(const UserMessageResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void UserMessageResponse::SharedCtor() {
  _cached_size_ = 0;
  sender_ = NULL;
  recipient_ = NULL;
  message_info_ = NULL;
  message_count_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UserMessageResponse::~UserMessageResponse() {
  SharedDtor();
}

void UserMessageResponse::SharedDtor() {
  if (this != default_instance_) {
    delete sender_;
    delete recipient_;
    delete message_info_;
  }
}

void UserMessageResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UserMessageResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UserMessageResponse_descriptor_;
}

const UserMessageResponse& UserMessageResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UserResponse_2eproto();
  return *default_instance_;
}

UserMessageResponse* UserMessageResponse::default_instance_ = NULL;

UserMessageResponse* UserMessageResponse::New() const {
  return new UserMessageResponse;
}

void UserMessageResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_sender()) {
      if (sender_ != NULL) sender_->::UserData::User_Info::Clear();
    }
    if (has_recipient()) {
      if (recipient_ != NULL) recipient_->::UserData::User_Info::Clear();
    }
    if (has_message_info()) {
      if (message_info_ != NULL) message_info_->::MessageData::Message_Info::Clear();
    }
    message_count_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UserMessageResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .UserData.User_Info sender = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_sender()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_recipient;
        break;
      }

      // optional .UserData.User_Info recipient = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_recipient:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_recipient()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_message_info;
        break;
      }

      // optional .MessageData.Message_Info message_info = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_message_info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_message_info()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_message_count;
        break;
      }

      // optional int32 message_count = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_message_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &message_count_)));
          set_has_message_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void UserMessageResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .UserData.User_Info sender = 1;
  if (has_sender()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->sender(), output);
  }

  // optional .UserData.User_Info recipient = 2;
  if (has_recipient()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->recipient(), output);
  }

  // optional .MessageData.Message_Info message_info = 3;
  if (has_message_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->message_info(), output);
  }

  // optional int32 message_count = 4;
  if (has_message_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->message_count(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* UserMessageResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .UserData.User_Info sender = 1;
  if (has_sender()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->sender(), target);
  }

  // optional .UserData.User_Info recipient = 2;
  if (has_recipient()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->recipient(), target);
  }

  // optional .MessageData.Message_Info message_info = 3;
  if (has_message_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->message_info(), target);
  }

  // optional int32 message_count = 4;
  if (has_message_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->message_count(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int UserMessageResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .UserData.User_Info sender = 1;
    if (has_sender()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->sender());
    }

    // optional .UserData.User_Info recipient = 2;
    if (has_recipient()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->recipient());
    }

    // optional .MessageData.Message_Info message_info = 3;
    if (has_message_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->message_info());
    }

    // optional int32 message_count = 4;
    if (has_message_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->message_count());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UserMessageResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UserMessageResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UserMessageResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UserMessageResponse::MergeFrom(const UserMessageResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_sender()) {
      mutable_sender()->::UserData::User_Info::MergeFrom(from.sender());
    }
    if (from.has_recipient()) {
      mutable_recipient()->::UserData::User_Info::MergeFrom(from.recipient());
    }
    if (from.has_message_info()) {
      mutable_message_info()->::MessageData::Message_Info::MergeFrom(from.message_info());
    }
    if (from.has_message_count()) {
      set_message_count(from.message_count());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UserMessageResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserMessageResponse::CopyFrom(const UserMessageResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserMessageResponse::IsInitialized() const {

  return true;
}

void UserMessageResponse::Swap(UserMessageResponse* other) {
  if (other != this) {
    std::swap(sender_, other->sender_);
    std::swap(recipient_, other->recipient_);
    std::swap(message_info_, other->message_info_);
    std::swap(message_count_, other->message_count_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UserMessageResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UserMessageResponse_descriptor_;
  metadata.reflection = UserMessageResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int IsExistNewMessageResponse::kIsExistFieldNumber;
#endif  // !_MSC_VER

IsExistNewMessageResponse::IsExistNewMessageResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void IsExistNewMessageResponse::InitAsDefaultInstance() {
}

IsExistNewMessageResponse::IsExistNewMessageResponse(const IsExistNewMessageResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void IsExistNewMessageResponse::SharedCtor() {
  _cached_size_ = 0;
  is_exist_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

IsExistNewMessageResponse::~IsExistNewMessageResponse() {
  SharedDtor();
}

void IsExistNewMessageResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void IsExistNewMessageResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* IsExistNewMessageResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return IsExistNewMessageResponse_descriptor_;
}

const IsExistNewMessageResponse& IsExistNewMessageResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UserResponse_2eproto();
  return *default_instance_;
}

IsExistNewMessageResponse* IsExistNewMessageResponse::default_instance_ = NULL;

IsExistNewMessageResponse* IsExistNewMessageResponse::New() const {
  return new IsExistNewMessageResponse;
}

void IsExistNewMessageResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    is_exist_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool IsExistNewMessageResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool is_exist = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_exist_)));
          set_has_is_exist();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void IsExistNewMessageResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool is_exist = 1;
  if (has_is_exist()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->is_exist(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* IsExistNewMessageResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bool is_exist = 1;
  if (has_is_exist()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->is_exist(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int IsExistNewMessageResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool is_exist = 1;
    if (has_is_exist()) {
      total_size += 1 + 1;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void IsExistNewMessageResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const IsExistNewMessageResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const IsExistNewMessageResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void IsExistNewMessageResponse::MergeFrom(const IsExistNewMessageResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_is_exist()) {
      set_is_exist(from.is_exist());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void IsExistNewMessageResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IsExistNewMessageResponse::CopyFrom(const IsExistNewMessageResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IsExistNewMessageResponse::IsInitialized() const {

  return true;
}

void IsExistNewMessageResponse::Swap(IsExistNewMessageResponse* other) {
  if (other != this) {
    std::swap(is_exist_, other->is_exist_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata IsExistNewMessageResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = IsExistNewMessageResponse_descriptor_;
  metadata.reflection = IsExistNewMessageResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace UserResponse

// @@protoc_insertion_point(global_scope)
